language: node_js

node_js:
  - "18"

cache:
  diretories:
    "node_modules"

before_script:
  - npm run coverage-test

after_success:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
